### Add a blog (replace TOKEN with value from login response)
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer TOKEN

{
  "title": "Test Blog",
  "author": "Me",
  "url": "https://example.com",
  "likes": 1
}